# Exported from Render on 2026-04-20T02:37:47Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: mongodb-crud-api
      runtime: node
      repo: https://github.com/TABUDII02/mongodb-crud-api
      plan: free
      envVars:
      - key: PORT
        sync: false
      - key: DB_URL
        sync: false
      - key: atlas_URL
        sync: false
      region: oregon
      buildCommand: npm install
      startCommand: node app.js
      autoDeployTrigger: commit
      rootDir: nosql-bootstrap-app
    - type: web
      name: zambosur-crafts
      runtime: static
      repo: https://github.com/TABUDII02/zambosur-crafts
      staticPublishPath: .
      autoDeployTrigger: commit
    - type: web
      name: mystor3
      runtime: static
      repo: https://github.com/TABUDII02/mystor3
      staticPublishPath: .
      autoDeployTrigger: commit
